service: spotify-playlist-splitter

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod
  region: eu-west-2
  environment: 
    SPOTIFY_CLIENT_SECRET: ${ssm:SPOTIFY_CLIENT_SECRET~true}

functions:
  playlistInfo:
    handler: handler.playlistInfo
    events:
     - http:
         path: /playlistInfo/{id}
         method: ANY
         cors: true

custom:
  webpack:
    linting: false

plugins:
  - serverless-webpack
  - serverless-offline
  