service: spotify-playlist-splitter

provider:
  name: aws
  runtime: nodejs10.x
  stage: prod           # Adapt to suit your staging strategy
  region: eu-central-1  # The same as in Atlas

functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /hello
         method: ANY
         cors: true

custom:
  bundle:
    linting: false

plugins:
  - serverless-bundle
  - serverless-offline
  